//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNKProjekti.Gjuhet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangAl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangAl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KNKProjekti.Gjuhet.LangAl", typeof(LangAl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulo.
        /// </summary>
        internal static string Anulo {
            get {
                return ResourceManager.GetString("Anulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistent.
        /// </summary>
        internal static string Asistent {
            get {
                return ResourceManager.GetString("Asistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatik.
        /// </summary>
        internal static string Automatik {
            get {
                return ResourceManager.GetString("Automatik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Fillimit.
        /// </summary>
        internal static string DataFillimit {
            get {
                return ResourceManager.GetString("DataFillimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Mbarimit.
        /// </summary>
        internal static string DataMbarimit {
            get {
                return ResourceManager.GetString("DataMbarimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Regjistrimit.
        /// </summary>
        internal static string DataRegjistrimit {
            get {
                return ResourceManager.GetString("DataRegjistrimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamentet.
        /// </summary>
        internal static string Departamentet {
            get {
                return ResourceManager.GetString("Departamentet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamenti.
        /// </summary>
        internal static string Departamenti {
            get {
                return ResourceManager.GetString("Departamenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditelindja.
        /// </summary>
        internal static string Ditelindja {
            get {
                return ResourceManager.GetString("Ditelindja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edito.
        /// </summary>
        internal static string Edito {
            get {
                return ResourceManager.GetString("Edito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronik.
        /// </summary>
        internal static string Elektronik {
            get {
                return ResourceManager.GetString("Elektronik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        internal static string Emri {
            get {
                return ResourceManager.GetString("Emri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri Departamentit.
        /// </summary>
        internal static string EmriDepartamentit {
            get {
                return ResourceManager.GetString("EmriDepartamentit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshije.
        /// </summary>
        internal static string Fshije {
            get {
                return ResourceManager.GetString("Fshije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafikat.
        /// </summary>
        internal static string Grafikat {
            get {
                return ResourceManager.GetString("Grafikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Ri.
        /// </summary>
        internal static string IRi {
            get {
                return ResourceManager.GetString("IRi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerko.
        /// </summary>
        internal static string Kerko {
            get {
                return ResourceManager.GetString("Kerko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerko sipas emrit.
        /// </summary>
        internal static string KerkoSipasEmrit {
            get {
                return ResourceManager.GetString("KerkoSipasEmrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompjuterik.
        /// </summary>
        internal static string Kompjuterik {
            get {
                return ResourceManager.GetString("Kompjuterik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbiemri.
        /// </summary>
        internal static string Mbiemri {
            get {
                return ResourceManager.GetString("Mbiemri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. Identifikues.
        /// </summary>
        internal static string NrIdentifikues {
            get {
                return ResourceManager.GetString("NrIdentifikues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. Kontaktues.
        /// </summary>
        internal static string NrKontaktues {
            get {
                return ResourceManager.GetString("NrKontaktues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NrPergjithshem.
        /// </summary>
        internal static string NrPergjithshem {
            get {
                return ResourceManager.GetString("NrPergjithshem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri i punetoreve per secilin departament.
        /// </summary>
        internal static string NrPunetorevePerSecilinDepartment {
            get {
                return ResourceManager.GetString("NrPunetorevePerSecilinDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri Llogaris.
        /// </summary>
        internal static string NumriLlogaris {
            get {
                return ResourceManager.GetString("NumriLlogaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paga.
        /// </summary>
        internal static string Paga {
            get {
                return ResourceManager.GetString("Paga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paga Totale.
        /// </summary>
        internal static string PagaTotale {
            get {
                return ResourceManager.GetString("PagaTotale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesat.
        /// </summary>
        internal static string Pagesat {
            get {
                return ResourceManager.GetString("Pagesat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozita.
        /// </summary>
        internal static string Pozita {
            get {
                return ResourceManager.GetString("Pozita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor.
        /// </summary>
        internal static string Profesor {
            get {
                return ResourceManager.GetString("Profesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punetor Ndihmes.
        /// </summary>
        internal static string PunetorNdihmes {
            get {
                return ResourceManager.GetString("PunetorNdihmes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raportet.
        /// </summary>
        internal static string Raportet {
            get {
                return ResourceManager.GetString("Raportet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referent.
        /// </summary>
        internal static string Referent {
            get {
                return ResourceManager.GetString("Referent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruaj.
        /// </summary>
        internal static string Ruaj {
            get {
                return ResourceManager.GetString("Ruaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruaj Ndryshimet.
        /// </summary>
        internal static string RuajNdryshimet {
            get {
                return ResourceManager.GetString("RuajNdryshimet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stafi.
        /// </summary>
        internal static string Stafi {
            get {
                return ResourceManager.GetString("Stafi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te Dhenat.
        /// </summary>
        internal static string TeDhenat {
            get {
                return ResourceManager.GetString("TeDhenat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udheheqesi Departamentit.
        /// </summary>
        internal static string UdheheqesiDepartamentit {
            get {
                return ResourceManager.GetString("UdheheqesiDepartamentit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vetit.
        /// </summary>
        internal static string Vetit {
            get {
                return ResourceManager.GetString("Vetit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjedh Grafikun.
        /// </summary>
        internal static string ZgjedhGrafikun {
            get {
                return ResourceManager.GetString("ZgjedhGrafikun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjedh Poziten.
        /// </summary>
        internal static string ZgjedhPoziten {
            get {
                return ResourceManager.GetString("ZgjedhPoziten", resourceCulture);
            }
        }
    }
}
